# Generated by Django 5.2.1 on 2025-05-25 09:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="caption",
            field=models.TextField(blank=True),
        ),
    ]
