# Generated by Django 5.2.1 on 2025-05-28 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_post_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="postUser",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
